const signature = `
oooo_ooo____oo_oooooo____oo______oo_oo_____oo_oooo____oooo____ooo____oo_
_oo__oooo___oo_oo____oo__oo______oo__oo___oo___oo___oo____oo__oooo___oo_
_oo__oo_oo__oo_oo_____oo_oo______oo___oo_oo____oo__oo______oo_oo_oo__oo_
_oo__oo__oo_oo_oo_____oo_oo______oo____ooo_____oo__oo______oo_oo__oo_oo_
_oo__oo___oooo_oo____oo___oo____oo____oo_oo____oo___oo____oo__oo___oooo_
oooo_oo____ooo_oooooo_______oooo_____oo___oo__oooo____oooo____oo____ooo_
________________________________________________________________________
`;
module.exports = signature;