title: INDUXION - A Redux Central Distributed State Management
email: devspace19@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  With INDUXION, you only have one data store for all your React App State Management
baseurl: "/induxion" # the subpath of your site, e.g. /blog
url: "https://devspace19.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: devspace19
github_username:  devspace19

# Build settings
theme: minima